[mgr]
ratio = [1, 3, 4]
linemode = "size"

[preview]
max_width = 1800
max_height = 2000

[opener]
play = [
	{ run = 'mpv --geometry=3200x1800 -- "$@"', orphan = true, for = "unix" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
